FROM delivery-kit-execution-broker:20261007.345
COPY broker/unchanged_seed_diagnosis.py /unchanged_seed_diagnosis.py
COPY broker/handoff_runtime.py /handoff_runtime.py
COPY broker/test_first_handoffs.py /test_first_handoffs.py
