FROM delivery-kit-execution-broker:20261008.356
COPY broker/timer_scope_replan.py /timer_scope_replan.py
COPY broker/technical_remediation_plan.py /technical_remediation_plan.py
COPY broker/request_scope_replan.py /request_scope_replan.py
COPY broker/harness_qualification.py /harness_qualification.py
COPY broker/remediation_author_context.py /remediation_author_context.py
COPY service_mode_timer_background_qualification.py /service_mode_timer_background_qualification.py
RUN PYTHONPATH=/ PYTHONDONTWRITEBYTECODE=1 python -c "import timer_scope_replan, harness_qualification, technical_remediation_plan"
