FROM delivery-kit-execution-broker:20261008.367-flat
COPY broker/server.py /broker.py
COPY broker/handoffs.py /handoffs.py
COPY broker/helper_cleanup.py /helper_cleanup.py
COPY broker/validation_job.py /validation_job.py
COPY broker/validation_recovery.py /validation_recovery.py
COPY broker/execution_diagnosis_recovery.py /execution_diagnosis_recovery.py
COPY broker/worker_recovery_transport.py /worker_recovery_transport.py
COPY broker/review_context_recovery.py /review_context_recovery.py
COPY broker/review_suite_rpc.py /review_suite_rpc.py
RUN PYTHONPATH=/ python -c "import validation_job,validation_recovery,handoffs"
